# Generated by Django 3.2.3 on 2021-05-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210523_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(2, 'PURCHASE'), (3, 'WITHDRAWAL'), (1, 'REFUND')]),
        ),
    ]
